config/routes.rb
Rails.application.routes.draw do

  get 'signin', to: 'sessions#new'
  post 'signin', to: 'sessions#create'
  delete 'signout', to: 'sessions#destroy'
  get 'cuisine', to: 'restaurants#search'
  get 'cuisines/:cuisine', to: 'restaurants#cuisine', as: 'cuisine_name'
  get 'events', to: 'events#list'
  post 'roulette', to: 'events#roulette'

  resources :yelp, only: [:index]
  resources :restaurants do
  	resources :events, shallow: true do
  		member do
  			post 'join'
        delete 'leave'
  		end
  	end
  end

  resources :users
  root 'restaurants#index'
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  belongs_to :restaurant
  has_many :events_users
  has_many :users, through: :events_users
  after_create :add_current_user_to_event_users
  scope :upcoming, -> { where("start > ? AND start < ?", Time.now, Time.now + 6.months) }
  scope :past, -> { where("start < ?", Time.now) }
  scope :joinable, -> { select('events.*, count(users.id) as user_count').joins(:users).group('events.id').having('user_count > 1 AND user_count < 6')}
  scope :roulettable, -> { upcoming.joinable }

  def add_current_user_to_event_users
  	users << user
  end

  def upcoming?
    start > Time.now ? true : false
  end

  def description
  	if Time.now < start
  		message = "are hanging out on "
  	else
  		message = "had a great time on "
  	end
  	message += start.strftime("%b. %d at %l:%M%P")
  end

end

app/models/events_user.rb
class EventsUser < ActiveRecord::Base
	belongs_to :event
	belongs_to :user
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :events
	geocoded_by :address
	after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }

	CUISINES = ["BBQ", "Mexican", "Ukranian", "Cajun", "French", "Trinidadian", "Indian", "Japanese", "Burgers", "German", "Steakhouse", "Asian", "Thai", "Ethiopian"]

	def display_cuisine
		CUISINES[cuisine]
	end

	def self.find_by_cuisine_name(cuisine)
		options = CUISINES.map(&:downcase)
		restaurants = Restaurant.where(cuisine: options.index(cuisine.downcase))
		restaurants = Restaurant.all if restaurants.empty?
		restaurants
	end

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :events
	has_many :events_users
	# has_many :events, through: :users
	validates_presence_of :first_name, :last_name, :email, :password, :address
	validates_uniqueness_of :email
	validates_presence_of :password_confirmation, on: :create
	validates_confirmation_of :password
	geocoded_by :address
	after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }
	has_attached_file :avatar, styles: { medium: "300x300#", thumb: "100x100#", icon: "35x35#" }, default_url: "/images/:style/missing.jpg"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/


	def full_name
		"#{first_name} #{last_name}"
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

	def current_user
		session[:user_id] ? User.find(session[:user_id]) : nil
	end

	def authenticate_user!
		unless current_user
			redirect_to signin_path, notice: "You must log in to do that."
		end
	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy, :join, :leave]
  before_action :set_restaurant, only: [:new, :create, :index]
  before_action :set_event, only: [:show, :join, :leave]

  def new
  	@event = Event.new
  end

  def index
    @events = @restaurant.events.upcoming
  end

  def list
    @events = Event.upcoming.joinable
    render :index
  end

  def edit
  end

  def show

  end

  def roulette
    @event = Event.roulettable.sample
    @event.users << current_user
    redirect_to @event, notice: %Q[Congrats you have been added to the event below. Not feeling it? Click here to #{view_context.link_to("leave", leave_event_path(@event), method: :delete)}.]
  end

  def join
    @event.users << current_user
    redirect_to @event, notice: "Added to event."
  end

  def leave
    @event.users.delete(current_user)
    redirect_to @event, notice: "Removed from event."
  end

  def create
    @restaurant.events.create(event_params)
    redirect_to restaurants_path, notice: "New event created."
  end

  private

  def event_params
    params.require(:event).permit(:start).merge(user: current_user)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def set_event
    @event = Event.find(params[:id])
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    if current_user
      @restaurants = Restaurant.near(current_user, 5)
    else
      @restaurants = Restaurant.all
    end
    @hash = Gmaps4rails.build_markers(@restaurants) do |restaurant, marker|
      marker.lat restaurant.latitude
      marker.lng restaurant.longitude
    end
  end

  def show
  	@restaurant = Restaurant.find(params[:id])
  end

  def new
  end

  def edit
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to new_restaurant_event_path(@restaurant)
    else
      redirect_to :back, notice: "Something went wrong."
    end
  end

  def search
    cuisine = Restaurant.find_by(cuisine: params[:cuisine])
    redirect_to cuisine_name_path(cuisine.display_cuisine)
  end

  def cuisine
    @restaurants = Restaurant.find_by_cuisine_name(params[:cuisine])
    @hash = Gmaps4rails.build_markers(@restaurants) do |restaurant, marker|
      marker.lat restaurant.latitude
      marker.lng restaurant.longitude
    end
    render :index
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :yelp_id, :phone, :address)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	@user = User.find_by(email: params[:email])
  	if @user and @user.password == params[:password]
  		session[:user_id] = @user.id
  		redirect_to root_path, notice: "Signed in."
  	else
  		redirect_to signin_path, notice: "There was a problem sigining in."
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to root_path, notice: "Logged out."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
  end

  def new
  	@user = User.new
  end

  def edit
  end

  def show
  end

  def create
  	@user = User.new(params_user)
  	if @user.save
      session[:user_id] = @user.id
  		redirect_to @user, notice: "New account created."
  	else
  		render :new
  	end
  end

  def update
    if @user.update(params_user)
      redirect_to @user, notice: "Profile updated."
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Account was deleted."
  end

  private

  def params_user
  	params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :address, :bio, :avatar)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/yelp_controller.rb
class YelpController < ApplicationController
	
	def index
		client = Yelp::Client.new({ consumer_key: ENV['HUNGRY_GAMES_CONSUMER_KEY'],
                            consumer_secret: ENV['HUNGRY_GAMES_CONSUMER_SECRET'],
                            token: ENV['HUNGRY_GAMES_TOKEN'],
                            token_secret: ENV['HUNGRY_GAMES_TOKEN_SECRET']
                          })
		
		if params[:cuisine]
			query = params[:cuisine]
		else
			query = "food"
		end
		@restaurants = client.search('10004', { term: query }).businesses
		@restaurants.map do |restaurant|
			record = Restaurant.find_by(yelp_id: restaurant.id)
			if record 
				record
			else
				restaurant
			end
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def current_user
		session[:user_id] ? User.find(session[:user_id]) : nil
	end

	def roulettable_events
		Event.roulettable.length > 0
	end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event.html.erb
<p>
	<%= link_to pluralize(event.users.size, 'foodee'), event %> <%= event.description %>

	<%= render 'join_event' %>
 </p>

app/views/events/_join_event.html.erb
<% if current_user %>
	<% if @event.users.include? current_user %>
		<p><%= link_to 'leave this event', leave_event_path(@event), method: :delete %></p>
	<% else %>
		<p><%= link_to 'join this event', join_event_path(@event), method: :post %></p>
	<% end %>
<% end %>

app/views/events/edit.html.erb
<h1>Events#edit</h1>
<p>Find me in app/views/events/edit.html.erb</p>

app/views/events/index.html.erb
<h1>Events</h1>
<p>Upcoming Events</p>
<%= render @events %>

app/views/events/new.html.erb
<h1>Pick a time to have a meal at <%= @restaurant.name %></h1>
<%= form_for [@restaurant, @event] do |f| %>
	<p>
		<%= f.label :start %>
		<%= f.datetime_select :start %>
	</p>
	<p>
		<%= f.submit "Book it!" %>
	</p>

<% end %>

app/views/events/show.html.erb
<h1><%= @event.restaurant.name %></h1>
<%= render 'join_event' %>

<p><%= @event.users.size %> foodees are coming on <%= @event.start.strftime("%b. %d at %l:%M%P") %></p>
<%= render @event.users %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HungryGames</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
	<span class="logo"><%= link_to 'HungryGames', root_path %></span>
	<nav>
		<% if current_user %>
			<span>Hello <%= current_user.first_name %></span>
			<%= link_to 'sign out', signout_path, method: :delete %>
			<%= link_to 'edit profile', edit_user_path(current_user) %>
		<% else %>
			<%= link_to 'sign in', signin_path %>
			<%= link_to 'sign up', new_user_path %>
		<% end %>
	</nav>
</header>
<main>
	<% if flash[:notice] %>
		<div class="notice"><%= flash[:notice].html_safe %></div>
	<% end %>
	<% if roulettable_events and current_user %>
		<%= link_to 'Roulette?', roulette_path, method: :post %>
	<% end %>

	<%= yield %>
</main>

</body>
</html>

app/views/restaurants/_restaurant.html.erb
<div class="restaurant">
	<h3><%= link_to restaurant.name, restaurant %></h3>
	<p><%= restaurant.display_cuisine %> | <%= restaurant.address %></p>
	<p><%= restaurant.phone %>
		<% if restaurant.events.upcoming.any? %>
			| <%= pluralize(restaurant.events.size, "upcoming event") %>  
		<% end %>
		<% if current_user %> 
		| <%= link_to 'new event', new_restaurant_event_path(restaurant) %> 
		<% end %>
	</p>
</div>
<hr>

app/views/restaurants/edit.html.erb
<h1>Restaurants#edit</h1>
<p>Find me in app/views/restaurants/edit.html.erb</p>

app/views/restaurants/index.html.erb
<h1>Restaurants (<%= @restaurants.size %>)</h1>
<div style='width: 100%;'>
  <div id="map" style='width: 100%; height: 400px;'></div>
</div>
<h3>Find a restaurant by cuisine:</h3>
<%= render 'shared/search' %>
<%= render @restaurants %>
<script type="text/javascript">
	handler = Gmaps.build('Google');
	handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
	  markers = handler.addMarkers(<%=raw @hash.to_json %>);
	  handler.bounds.extendWith(markers);
	  handler.fitMapToBounds();
	});
</script>

app/views/restaurants/new.html.erb
<h1>Restaurants#new</h1>
<p>Find me in app/views/restaurants/new.html.erb</p>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<p><%= @restaurant.address %></p>
<% if @restaurant.events.upcoming.any? %>
	<h3>Upcoming Events</h3>
	<%= render @restaurant.events.upcoming %>
<% end %>

<% if @restaurant.events.past.any? %>
	<h3>Past Events</h3>
	<%= render @restaurant.events.past %>
<% end %>

app/views/shared/_search.html.erb
<%= form_tag '/yelp', method: :get do %>
	<%= select_tag(:cuisine, options_for_select(Restaurant::CUISINES.map.with_index { |c,i| [c, c] })) %>
	<%= submit_tag "search" %>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user, html: { multipart: true } do |f| %>
	<% if @user.errors.any? %>
		<div class="alert">
			<% @user.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</div>
	<% end %>
	
	<p>
		<%= f.label :first_name, "First Name" %>
		<%= f.text_field :first_name, required: true, placeholder: "First Name" %>
	</p>
	<p>
		<%= f.label :last_name, "Last Name" %>
		<%= f.text_field :last_name, required: true, placeholder: "Last Name" %>
	</p>
	<p>
		<%= f.label :email %>
		<%= f.email_field :email, required: true, placeholder: "Email" %>
	</p>
	<% if @user.new_record? %>
		<p>
			<%= f.label :password %>
			<%= f.password_field :password, required: true, placeholder: "Password" %>
		</p>
		<p>
			<%= f.label :password_confirmation %>
			<%= f.password_field :password_confirmation, required: true, placeholder: "Password" %>
		</p>
	<% end %>
	<p>
		<%= f.label :address %>
		<%= f.text_field :address %>
	</p>
	<p>
		<%= f.label :bio %>
		<%= f.text_area :bio %>
	</p>
	<p>
		<%= f.label :avatar %>
		<%= f.file_field :avatar %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/users/_user.html.erb
<h3><%= image_tag user.avatar.url(:icon) %>
	<%= link_to user.full_name, user %>
</h3>

app/views/users/edit.html.erb
<h1>Editing Profile</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1>Restaurants</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Sign up!</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<%= image_tag @user.avatar.url(:medium) %>
<h1><%= @user.full_name %></h1>
<% if @user.bio.blank? %>
	<p><%= @user.full_name %> is mysterious.</p>
<% else %>
	<p><%= @user.bio %></p>
<% end %>

app/views/yelp/index.html.erb
<%= render 'shared/search' %>
<ol>
<% @restaurants.each do |restaurant| %>
	<li><%= restaurant.name %> (<%= link_to 'create an event', restaurants_path(params: {restaurant: {name: restaurant.name, yelp_id: restaurant.id, address: restaurant.location.display_address.join(" ")}}), method: :post %>)</li>
<% end %>
</ol>